{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gitlab-rss-sync.fullname" . }}-secrets
  labels:
    {{- include "gitlab-rss-sync.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.items }}
  {{- range .Values.secrets.items }}
  {{ .key }}: {{ .value | default "" | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }}
